---
title: "R_LEGO_PROJECT"
author: "Justyna"
date: "2023-12-04"
output:
  html_document: 
    toc: yes
    toc_float: yes
    theme: readable
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(ggsci)
library(shiny)
library(plotly)
library(flexdashboard)
```

```{r load_data, echo=FALSE}

load_csv_gz_data <- function(file_path) {
    data <- read.csv(gzfile(file_path))
  return(data)
}

colors <- load_csv_gz_data("rebrickable/colors.csv.gz")
elements <- load_csv_gz_data("rebrickable/elements.csv.gz")
inventories <- load_csv_gz_data("rebrickable/inventories.csv.gz")
inventory_minifigs <- load_csv_gz_data("rebrickable/inventory_minifigs.csv.gz")
inventory_parts <- load_csv_gz_data("rebrickable/inventory_parts.csv.gz")
inventory_sets <- load_csv_gz_data("rebrickable/inventory_sets.csv.gz")
minifigs <- load_csv_gz_data("rebrickable/minifigs.csv.gz")
part_categories <-load_csv_gz_data("rebrickable/part_categories.csv.gz")
part_relationships <-load_csv_gz_data("rebrickable/part_relationships.csv.gz")
parts <-load_csv_gz_data("rebrickable/parts.csv.gz")
sets <-load_csv_gz_data("rebrickable/sets.csv.gz")
themes <- load_csv_gz_data("rebrickable/themes.csv.gz")

```
## R Executive summary

```{r summary}

head(colors)
head(elements)
head(inventories)
head(inventory_minifigs)
head(inventory_parts)
head(inventory_sets)
head(minifigs)
head(part_categories)
head(part_relationships)
head(parts)
head(sets)
head(themes)

```

